### PR TITLE
Test ruby 2.5.7/2.6.5, see: ManageIQ/manageiq#19414

### PR DESCRIPTION
**Pull request by jrafanie**
Test ruby 2.5.7/2.6.5, see: ManageIQ/manageiq#19414

### CODE REVIEW

**Comment by Fryguy** [comment]
@carbonin @jrafanie FYI - https://github.com/ManageIQ/container-httpd/blob/master/Dockerfile#L84-L85

**Comment by jrafanie** [comment]
> @carbonin @jrafanie FYI - https://github.com/ManageIQ/container-httpd/blob/master/Dockerfile#L84-L85

Ruby 2.5.x should be fine to update in the Dockerfile though right?  It looks like it's just the 2.3.1 lines:
https://github.com/ManageIQ/container-httpd/blob/4e6f67f199e87a5c5c96abcfa79cd9ddf641fd7e/Dockerfile#L73-L85


@simaishi @carbonin I also noticed we're building centos 7 upstream even though http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/ is out.  There's so many references to centos7/epel7 here:

https://github.com/ManageIQ/manageiq-appliance-build/blob/0a0d04bfe53601ade18f08b82c96905e22d709fe/kickstarts/partials/main/repos.ks.erb#L2-L16... some are duplicated in the Dockerfile... will have to discuss with you how we upgrade those.

**Comment by simaishi** [comment]
> @simaishi @carbonin I also noticed we're building centos 7 upstream even though http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/ is out.

I'm working on CentOS 8 update for appliance right now, but this will take a bit of time as I need to build a new build machine (which is where I'm at)

**Comment by jrafanie** [comment]
> I'm working on CentOS 8 update for appliance right now, but this will take a bit of time as I need to setup a new build machine (which is where I'm at)

Ok, great!  I'm trying jemalloc on epel8 and noticed the os difference in manageiq

**Pull request merged**
